<?php 
return array (
  'site_name' => '微专家微营销系统',
  'site_title' => '微信公众平台',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://120.25.218.254/index.php',
  'site_my' => '微营销',
  'server_key' => 'bc9ed510a91c14331cf2f6ce4169807b',
  'server_topdomain' => 'http://120.25.218.254/index.php',
  'connectout' => '用户已到期，请联系管理员或客服充值',
  'ischeckuser' => 'true',
  'reg_needmp' => 'true',
  'open_biz' => '1',
  'isclosekuser' => 'false',
  'server_discuz' => '',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'router_key' => '',
  'ipc' => '',
  'site_qq' => '',
  'site_mp' => '',
  'site_kfqq' => '',
  'site_qqqun' => '',
  'site_tel' => '',
  'site_adress' => '',
  'baidu_map_api' => '908bb5a05fa5f839dafeb1a957c7ed51',
  'site_email' => '',
  'keyword' => '',
  'content' => '',
  'countsz' => '',
  'copyright' => 'Copyright (c) 2015 微营销系统 版权所有',
  'ucenter_db_set' => '',
  'ucenter_web_set' => '',
);